// ============================================================
// JOKEUP - Banc de Dades de Contingut
// 900+ preguntes, reptes, declaracions i paraules
// ============================================================

const DATA = {

  // ===================== VERITAT O REPTE =====================
  truthOrDare: {
    truths: {
      suau: [
        "Quina és la cosa més vergonyosa que t'ha passat en públic?",
        "Quin és el teu plaer culpable que ningú sap?",
        "Quina mentida has dit recentment?",
        "Quin és el teu major fear irracional?",
        "Quina és la pitjor cita que has tingut mai?",
        "Quin secret petit guardes que no és greu però et fa vergonya?",
        "Quina és la cosa més infantil que encara fas?",
        "Quin és el teu talent ocult més ridícul?",
        "Quina cançó cursi cantes quan estàs sol/a?",
        "Quin és l'últim stalkeo que has fet a les xarxes?",
        "Has copiat mai en un examen? Com?",
        "Quina és la mentida més gran que has dit als teus pares?",
        "Quin és el somni més estrany que has tingut?",
        "Quina pel·lícula o sèrie t'ha fet plorar?",
        "Quin és el teu defecte que més t'agradaria canviar?",
        "Quina és la cosa més random que tens al mòbil?",
        "Quin missatge t'avergonyiria que es llegís en veu alta?",
        "Quina és la excusa més creativa que has inventat?",
        "Has fingit mai estar malalt/a per no anar a algun lloc?",
        "Quina és la cosa més rara que has buscat a Google?",
        "Quin és el teu crush de famós/a que et fa vergonya admetre?",
        "Quina foto de la galeria t'avergonyiria més ensenyar?",
        "Has mentit mai sobre la teva edat? Per què?",
        "Quina és la cosa més barata que has fet mai?",
        "Quin hàbit tens que consideraries una mica brut?"
      ],
      normal: [
        "Quina és la cosa més boja que has fet per impressionar algú?",
        "Has enviat mai un missatge a la persona equivocada? Què deia?",
        "Quin és el teu major penediment amorós?",
        "Quina és la cosa més il·legal que has fet?",
        "Has flirtejat mai amb algú d'aquest grup?",
        "Quin és el pitjor regal que has rebut i has fingit que t'agradava?",
        "Has dit mai 't'estimo' sense sentir-ho?",
        "Quina és la cosa més egoista que has fet?",
        "Has robat mai alguna cosa? Què?",
        "Quin és el teu ex/crush que et faria més vergonya que es sabés?",
        "Quina és la teva opinió impopular que mai dius en veu alta?",
        "Has parlat mai malament d'algú d'aquest grup? De qui?",
        "Quin és el moment més humiliant de la teva vida amorosa?",
        "Has ghostejat mai algú? Per què?",
        "Quina és la promesa més important que has trencat?",
        "Has fingit mai un orgasme?",
        "Quina és la mentida que dius més sovint?",
        "De qui del grup tens més enveja i per què?",
        "Quina és la cosa més incòmoda que has vist fer a un amic?",
        "Has tingut mai un crush amb l'ex d'un amic/a?",
        "Quin és el pitjor consell que has donat mai?",
        "Has simulat mai estar borratxo/a? Per què?",
        "Quina és la cosa que faries si sabessis que ningú et jutjaria?",
        "Has estalat mai amb algú que no hauries d'haver-ho fet?",
        "Quin del grup creus que té més secrets?"
      ],
      picant: [
        "Quina és la teva fantasia més inconfessable?",
        "Quin és el lloc més estrany on has fet un petó?",
        "Has tingut mai un somni eròtic amb algú d'aquest grup?",
        "Quina és la cosa més atrevida que has fet en una festa?",
        "Quin és el teu tipus que et fa vergonya admetre?",
        "Quina és l'app de cites més vergonyosa que has usat?",
        "Has enviat mai un nude? T'has penedit?",
        "Quin és el DM més atrevit que has enviat o rebut?",
        "Quina és la teva experiència més incòmoda romanticament?",
        "Has fet mai alguna cosa sexual en un lloc públic?",
        "Quina és la teva tècnica de seducció més patètica?",
        "Has tingut mai un llit amb algú que no recordaves el nom?",
        "Quin és el teu turn-on més estrany?",
        "Has fet mai sexting? Amb qui?",
        "Quina és la pitjor experiència que has tingut al llit?",
        "Has tingut mai un trio o t'agradaria?",
        "Quina és la cosa més vergonyosa que t'ha passat durant el sexe?",
        "Has mirat mai porno amb algú?",
        "Quina és la teva posició preferida?",
        "Has tingut mai un crush amb el/la profe?",
        "Quin és el lloc més públic on has tingut sexe?",
        "Has fet mai un petó amb més d'una persona la mateixa nit?",
        "Quina és la cosa més salvatge que has fet borratxo/a?",
        "Has anat mai a un lloc sense roba interior?",
        "Amb quantes persones has estat?"
      ],
      extrem: [
        "Confessa el secret més fosc que guardes d'algú d'aquest grup.",
        "Quina és la cosa més il·legal que has fet i no t'han enxampat?",
        "Si haguessis de liar-te amb algú d'aquest grup, amb qui?",
        "Quina és la veritat més dura que mai has dit a algú?",
        "Quin és el teu fetitxe sexual?",
        "Has trampejat mai en una relació?",
        "Quina és la cosa de la que més t'avergonyeixes en tota la teva vida?",
        "Has fet mai alguna cosa que podria arruïnar una amistat d'aquest grup?",
        "Si poguessis eliminar un record de la teva vida, quin seria?",
        "Has desitjat mai estar amb la parella d'un amic/a?",
        "Quina és la cosa més tòxica que has fet en una relació?",
        "Si el teu mòbil es llegís en veu alta ara, què seria el pitjor?",
        "Has fingit mai ser algú que no ets per agradar a algú?",
        "Quina és la cosa que mai perdonaries?",
        "Quin és el pitjor error que has comès borratxo/a?",
        "Has manipulat mai emocionalment algú? Com?",
        "Quina és la cosa més perillosa que has fet per diversió?",
        "Si poguessis canviar una cosa del teu passat, quina seria?",
        "Has trair mai la confiança d'algú proper? Com?",
        "Quina és la doble vida o façana que mantens?"
      ]
    },
    dares: {
      suau: [
        "Fes 10 flexions ara mateix.",
        "Imita algú del grup fins que endevinin qui és.",
        "Canta el tornada d'una cançó a ple pulmó.",
        "Fes la teva millor cara de selfie i que algú la publiqui.",
        "Balla durant 30 segons sense música.",
        "Deixa que el grup et posi un nou nom al WhatsApp.",
        "Fes un rap improvisat sobre la persona de la teva dreta.",
        "Truca a un contacte aleatori i diga-li que l'estimes.",
        "Fes d'accent andalús durant 2 rondes.",
        "Posa't gel a la cara durant 10 segons.",
        "Fes 20 salts d'estrella.",
        "Imita el teu animal preferit durant 1 minut.",
        "Deixa que algú del grup et faci un pentinat nou.",
        "Publica una story d'Instagram fent una cara ridícula.",
        "Fes un monòleg de 30 segons sobre un tema random.",
        "Camina com un model per la sala durant 15 segons.",
        "Canta 'Happy Birthday' amb accent francès.",
        "Fes una declaració d'amor dramàtica a un objecte de la sala.",
        "Menja alguna cosa barrejada que triï el grup (de la cuina).",
        "Fes servir només la mà no dominant durant 3 rondes.",
        "Fes la imitació d'un influencer famós.",
        "Envia un àudio de WhatsApp cantant al teu últim xat.",
        "Fes 30 segons de plank.",
        "Parla amb rima durant 2 rondes.",
        "Fes un tutorial de maquillatge imaginari."
      ],
      normal: [
        "Deixa que el grup revisi les teves últimes cerques de Google.",
        "Envia 'Em fas ràbia' a l'últim contacte del WhatsApp.",
        "Deixa que algú publiqui el que vulgui a les teves xarxes.",
        "Fes un TikTok ridícul i puja'l.",
        "Beu un got d'una barreja que triï el grup.",
        "Truca a la teva mare/pare i diga-li que et cases.",
        "Deixa que el grup llegeixi els teus últims 5 missatges.",
        "Fes un petó a la mà de la persona de l'esquerra.",
        "Posa't roba d'algú altre del grup.",
        "Fes una serenata a algú del grup.",
        "Dona el teu mòbil al grup durant 1 minut perquè facin el que vulguin.",
        "Publica una foto vergonyosa a Instagram (la pots borrar demà).",
        "Envia un missatge de veu cantant al teu crush.",
        "Deixa que algú et maquilli amb els ulls tancats.",
        "Fes un massatge de 30 segons a qui triï el grup.",
        "Imita la persona del teu contacte que menys et cau bé.",
        "Mostra la teva última foto de la galeria.",
        "Envia un emoji de cor a les últimes 5 persones del WhatsApp.",
        "Fes un discurs presidencial sobre per què el grup hauria de fer-te líder.",
        "Intenta lligar amb algú del grup de la manera més cringe possible.",
        "Mantingues contacte visual amb algú durant 30 segons sense riure.",
        "Fes un ball sexi amb una escombra o mopa.",
        "Deixa que el grup canviï la teva foto de perfil.",
        "Envia 'Necessito parlar amb tu...' al teu ex.",
        "Fes accent italià durant les pròximes 3 rondes."
      ],
      picant: [
        "Fes un petó al coll de qui triï el grup.",
        "Fes un striptease (només la samarreta!).",
        "Asseu-te a la falda d'algú durant 2 rondes.",
        "Fes un body shot amb algú del grup.",
        "Deixa que algú et deixi un xuclot (visible!).",
        "Balla un reggaeton amb algú del grup.",
        "Susurra alguna cosa sexy a l'orella de qui triï el grup.",
        "Fes un petó a algú del grup (a la galta val).",
        "Juga a la botella amb el grup (un petó ràpid).",
        "Deixa que algú t'escrigui alguna cosa al cos amb retolador.",
        "Fes un massatge sensual d'1 minut a qui triï el grup.",
        "Ensenya la roba interior sense treure't els pantalons.",
        "Fes un lap dance de 15 segons a una cadira.",
        "Envia un missatge atrevit a l'últim contacte del WhatsApp.",
        "Juga la pròxima ronda en roba interior (si tens banyador val).",
        "Fes un petó de pel·lícula amb algú del grup.",
        "Deixa que algú et posi gel dins la samarreta.",
        "Fes un espectacle de talents sexy de 30 segons.",
        "Posa una cançó sexy i balla-la amb conviction.",
        "Deixa que algú del grup et faci una foto provocativa (que puguis borrar)."
      ],
      extrem: [
        "Truca al teu crush i confessa els teus sentiments.",
        "Publica 'Estic solter/a i disponible' a totes les xarxes.",
        "Fes un petó de 10 segons amb qui triï el grup.",
        "Dona el teu mòbil 5 minuts perquè el grup faci EL QUE VULGUI.",
        "Envia un missatge al teu ex dient 'Et trobo a faltar'.",
        "Fes un strip poker d'una sola ronda.",
        "Truca a un contacte aleatori i canta-li una cançó d'amor sencera.",
        "Publica la foto més vergonyosa que tinguis a Instagram.",
        "Fes un petó a tres persones del grup.",
        "Surt al balcó/carrer i crida 'ESTIC ENAMORAT/DA DE [nom que triï el grup]!'",
        "Deixa que el grup enviï un missatge des del teu mòbil a qui vulguin.",
        "Fes la resta del joc sense samarreta.",
        "Confessa alguna cosa que mai has dit a ningú del grup en veu alta.",
        "Deixa que algú publiqui una story d'Instagram des del teu compte.",
        "Fes un karaoke complet d'una cançó que triï el grup."
      ]
    }
  },

  // ===================== JO MAI MAI =====================
  neverHaveIEver: {
    suau: [
      "Jo mai mai... he fingit que m'agradava un regal.",
      "Jo mai mai... he cantat a la dutxa.",
      "Jo mai mai... he plorat amb una pel·lícula de Disney.",
      "Jo mai mai... he menjat menjar del terra.",
      "Jo mai mai... he fingit estar ocupat/da per evitar algú.",
      "Jo mai mai... he stalkejat un ex a les xarxes.",
      "Jo mai mai... he mentit sobre la meva edat.",
      "Jo mai mai... he parlat sol/a.",
      "Jo mai mai... he buscat el meu propi nom a Google.",
      "Jo mai mai... he fet veure que no he vist algú pel carrer.",
      "Jo mai mai... he dormit fins les 3 de la tarda.",
      "Jo mai mai... he enviat un missatge i l'he eliminat ràpidament.",
      "Jo mai mai... he rigut en un moment totalment inapropiat.",
      "Jo mai mai... he fingit saber d'un tema del que no tenia ni idea.",
      "Jo mai mai... he plorat per una cançó.",
      "Jo mai mai... m'he caigut en públic.",
      "Jo mai mai... he oblidat l'aniversari d'algú important.",
      "Jo mai mai... he après a cuinar un plat per impressionar algú.",
      "Jo mai mai... he cancel·lat plans perquè preferia quedar-me al sofà.",
      "Jo mai mai... he posat 'jajaja' sense riure realment.",
      "Jo mai mai... m'he fet un selfie al lavabo.",
      "Jo mai mai... he dit que estava de camí quan encara era a casa.",
      "Jo mai mai... he llegit un missatge i he esperat hores per contestar.",
      "Jo mai mai... he vist una sèrie sencera en un dia.",
      "Jo mai mai... m'he oblidat del nom d'algú just després de presentar-nos."
    ],
    festa: [
      "Jo mai mai... m'he emborratxat tant que no recordava res.",
      "Jo mai mai... he vomitat per l'alcohol.",
      "Jo mai mai... he dormit a casa d'un desconegut.",
      "Jo mai mai... he fet skinny dipping.",
      "Jo mai mai... he besat algú que acabava de conèixer.",
      "Jo mai mai... he anat a treballar/classe amb ressaca.",
      "Jo mai mai... he begut directament de l'ampolla.",
      "Jo mai mai... he fet un karaoke borratxo/a.",
      "Jo mai mai... m'he despertat en un lloc i no sabia on era.",
      "Jo mai mai... he perdut el mòbil en una festa.",
      "Jo mai mai... m'he colat en algun lloc.",
      "Jo mai mai... he jugat a la botella.",
      "Jo mai mai... he dit 't'estimo' a un desconegut borratxo/a.",
      "Jo mai mai... he trucat a l'ex borratxo/a.",
      "Jo mai mai... he ballat sobre una taula.",
      "Jo mai mai... m'he quedat dormit/da a una festa.",
      "Jo mai mai... he barrejat begudes i m'ha anat malament.",
      "Jo mai mai... he fet algo de lo que em vaig penedir l'endemà.",
      "Jo mai mai... he perdut la cartera en una nit de festa.",
      "Jo mai mai... m'he despertat amb un morat misteriós.",
      "Jo mai mai... he anat a una festa sense ser convidat/da.",
      "Jo mai mai... he sortit de festa un dilluns.",
      "Jo mai mai... he begut abans de les 12 del migdia.",
      "Jo mai mai... he fet pre-game sol/a.",
      "Jo mai mai... he fet un botellon."
    ],
    picant: [
      "Jo mai mai... he enviat un nude.",
      "Jo mai mai... he besat algú del mateix sexe.",
      "Jo mai mai... he tingut un rotllo d'una nit.",
      "Jo mai mai... he fet servir una app de cites.",
      "Jo mai mai... he besat algú d'aquest grup.",
      "Jo mai mai... he tingut un crush amb algú d'aquest grup.",
      "Jo mai mai... he fet sexting.",
      "Jo mai mai... he estat amb algú en secret.",
      "Jo mai mai... he mirat porno al mòbil en un lloc públic.",
      "Jo mai mai... he tingut un somni eròtic amb algú d'aquí.",
      "Jo mai mai... m'han pillat fent algo íntim.",
      "Jo mai mai... he fingit un orgasme.",
      "Jo mai mai... he anat a un sex shop.",
      "Jo mai mai... he fet un petó a tres persones la mateixa nit.",
      "Jo mai mai... he lligat amb l'ex d'un amic/a.",
      "Jo mai mai... he estat amb dues persones el mateix dia.",
      "Jo mai mai... he rebut o enviat una foto comprometedora.",
      "Jo mai mai... m'he enamorat d'un amic/a.",
      "Jo mai mai... he provat joguines sexuals.",
      "Jo mai mai... he tingut un amant secret.",
      "Jo mai mai... he estat celós/a d'algú d'aquest grup.",
      "Jo mai mai... he fet sexe a casa d'algú altre sense permís.",
      "Jo mai mai... he fantasiejat amb algú que no hauria.",
      "Jo mai mai... he flirtejat amb algú per aconseguir alguna cosa.",
      "Jo mai mai... he estat amb algú 10+ anys més gran."
    ],
    extrem: [
      "Jo mai mai... he participat en un trio.",
      "Jo mai mai... he enganyat la meva parella.",
      "Jo mai mai... he destrossat la relació d'algú altre.",
      "Jo mai mai... he robat alguna cosa d'una botiga.",
      "Jo mai mai... he conduit borratxo/a.",
      "Jo mai mai... he tingut relacions en un lloc molt públic.",
      "Jo mai mai... he mentit a la policia.",
      "Jo mai mai... m'he liat amb el germà/germana d'un amic/a.",
      "Jo mai mai... he gravat un moment íntim.",
      "Jo mai mai... he fet algo sexual per diners o favors.",
      "Jo mai mai... he mantingut una doble vida amorosa.",
      "Jo mai mai... he llegit el mòbil de la meva parella a amagades.",
      "Jo mai mai... he destrossat propietat aliena intencionadament.",
      "Jo mai mai... he tingut un crush amb el pare/mare d'un amic.",
      "Jo mai mai... he consumit drogues il·legals.",
      "Jo mai mai... he fet xantatge emocional.",
      "Jo mai mai... he entrat a un lloc prohibit.",
      "Jo mai mai... he simulat ser algú altre online.",
      "Jo mai mai... he participat en una baralla física.",
      "Jo mai mai... m'he venjat d'algú de manera calculada."
    ]
  },

  // ===================== QUI ÉS MÉS PROBABLE =====================
  mostLikelyTo: {
    suau: [
      "Qui és més probable que arribi tard al seu propi casament?",
      "Qui és més probable que es faci famós/a?",
      "Qui és més probable que sobrevisqui a una illa deserta?",
      "Qui és més probable que plori amb un anunci de TV?",
      "Qui és més probable que es casi primer/a?",
      "Qui és més probable que es gasti tots els diners en menjar?",
      "Qui és més probable que es quedi dormit/da a qualsevol lloc?",
      "Qui és més probable que es perdi en una ciutat nova?",
      "Qui és més probable que guanyi un reality show?",
      "Qui és més probable que adopti 10 gats?",
      "Qui és més probable que es converteixi en influencer?",
      "Qui és més probable que obri un restaurant?",
      "Qui és més probable que viatgi pel món sencer?",
      "Qui és més probable que escrigui un llibre?",
      "Qui és més probable que es presenti a un concurs de TV?",
      "Qui és més probable que tingui una vida doble secreta?",
      "Qui és més probable que visqui fins als 100 anys?",
      "Qui és més probable que inventi alguna cosa?",
      "Qui és més probable que estigui en una banda?",
      "Qui és més probable que acabi vivint en una furgoneta?",
      "Qui és més probable que es tatui el nom d'algú?",
      "Qui és més probable que sigui el primer a marxar d'una festa?",
      "Qui és més probable que faci un discurs viral?",
      "Qui és més probable que sigui detectiu?",
      "Qui és més probable que guanyi la loteria i la malgasti?"
    ],
    festa: [
      "Qui és més probable que acabi ballant a sobre d'una taula?",
      "Qui és més probable que perdi el mòbil aquesta nit?",
      "Qui és més probable que vomiti primer?",
      "Qui és més probable que truqui a l'ex borratxo/a?",
      "Qui és més probable que comenci una baralla absurda?",
      "Qui és més probable que faci un striptease?",
      "Qui és més probable que s'adormi al lavabo?",
      "Qui és més probable que besi un desconegut avui?",
      "Qui és més probable que digui 't'estimo' a tothom?",
      "Qui és més probable que perdi la roba a la festa?",
      "Qui és més probable que acabi cantant karaoke sol/a?",
      "Qui és més probable que es desperti en un lloc desconegut?",
      "Qui és més probable que faci algo que negarà demà?",
      "Qui és més probable que barreji totes les begudes?",
      "Qui és més probable que publiqui algo vergonyós a Instagram?",
      "Qui és més probable que vulgui anar a una altra festa després?",
      "Qui és més probable que flirteji amb el cambrer/a?",
      "Qui és més probable que acabi plorant?",
      "Qui és més probable que es penedeixi d'algo demà al matí?",
      "Qui és més probable que sigui l'últim en marxar?",
      "Qui és més probable que perdi les claus de casa?",
      "Qui és més probable que es quedi sense bateria?",
      "Qui és més probable que demani menjar a les 4am?",
      "Qui és més probable que faci un discurs borratxo/a?",
      "Qui és més probable que faci algo il·legal aquesta nit?"
    ],
    picant: [
      "Qui és més probable que tingui un perfil secret de Tinder?",
      "Qui és més probable que hagi enviat un nude equivocat?",
      "Qui és més probable que tingui un rotllo amagat?",
      "Qui és més probable que lligui amb algú d'aquest grup?",
      "Qui és més probable que sigui increïble al llit?",
      "Qui és més probable que tingui les fantasies més salvatges?",
      "Qui és més probable que faci un trio?",
      "Qui és més probable que enganyés la seva parella?",
      "Qui és més probable que es liés amb un famós?",
      "Qui és més probable que tingui un OnlyFans secret?",
      "Qui és més probable que hagi tingut un rotllo d'una nit del que es penedeix?",
      "Qui és més probable que flirteji amb qualsevol que respiri?",
      "Qui és més probable que hagi mentit sobre amb quantes persones ha estat?",
      "Qui és més probable que estigui pensant en sexe ara mateix?",
      "Qui és més probable que hagi fet sexe en un lloc públic?",
      "Qui és més probable que tingui el historial de navegació més vergonyós?",
      "Qui és més probable que accepti un sugar daddy/mommy?",
      "Qui és més probable que s'enamori del seu/seva millor amic/a?",
      "Qui és més probable que sigui la persona més kinky del grup?",
      "Qui és més probable que hagi estat amb algú d'un altre del grup?"
    ]
  },

  // ===================== QUÈ PREFEREIXES? =====================
  wouldYouRather: {
    suau: [
      { a: "Poder volar", b: "Poder llegir ments" },
      { a: "Viure 200 anys", b: "Poder viatjar en el temps" },
      { a: "Ser invisible", b: "Poder teletransportar-te" },
      { a: "No dormir mai més", b: "No menjar mai més" },
      { a: "Viure sense mòbil", b: "Viure sense internet" },
      { a: "Ser el més intel·ligent del món", b: "Ser el més atractiu del món" },
      { a: "Poder parlar amb animals", b: "Parlar tots els idiomes" },
      { a: "Ser milionari sense amics", b: "Ser pobre amb els millors amics" },
      { a: "Viure a la platja", b: "Viure a la muntanya" },
      { a: "Saber com moriràs", b: "Saber quan moriràs" },
      { a: "Tenir memòria fotogràfica", b: "Tenir reflexos perfectes" },
      { a: "Poder pausar el temps", b: "Poder rebobinar el temps" },
      { a: "Viure en el passat", b: "Viure en el futur" },
      { a: "Mai més tenir Wi-Fi", b: "Mai més menjar el teu plat preferit" },
      { a: "Ser famós i odiat", b: "Ser desconegut i estimat" },
      { a: "Poder canviar de gènere un dia", b: "Poder canviar d'edat un dia" },
      { a: "Tenir una capa d'invisibilitat", b: "Tenir una vareta màgica" },
      { a: "Viure en una pel·lícula d'acció", b: "Viure en una comèdia romàntica" },
      { a: "Tenir tot el temps del món", b: "Tenir tots els diners del món" },
      { a: "Saber tot sobre el teu futur", b: "Poder canviar una cosa del passat" }
    ],
    festa: [
      { a: "Beure només cervesa la resta de la vida", b: "Beure només shots la resta de la vida" },
      { a: "No poder beure mai més alcohol", b: "Estar una mica borratxo/a SEMPRE" },
      { a: "Cantar karaoke cada cop que entres a un bar", b: "Ballar salsa cada cop que sona música" },
      { a: "Sortir de festa cada nit", b: "No sortir mai més de festa" },
      { a: "Tenir ressaca permanent", b: "No poder emborratxar-te mai" },
      { a: "Que tots els teus borratxos es gravin", b: "Que tots els teus exs vinguin a cada festa" },
      { a: "Ser el DJ oficial de cada festa", b: "Ser el barman oficial de cada festa" },
      { a: "Dir sempre la veritat borratxo/a", b: "Fer sempre el que et repten borratxo/a" },
      { a: "Portar disfresa a cada festa", b: "Anar descalç/a a cada festa" },
      { a: "Que la teva mare vegi tots els teus stories de festa", b: "Que el teu cap vegi tots els teus stories" },
      { a: "Només poder beure d'un sabor", b: "Només poder menjar un plat per sempre" },
      { a: "Anar de festa cada divendres obligat", b: "No poder sortir cap divendres" },
      { a: "Acabar cada festa cantant", b: "Acabar cada festa plorant d'emoció" },
      { a: "Ser l'ànima de la festa", b: "Ser la persona amb qui tothom vol parlar en privat" },
      { a: "Fer un viatge amb el grup cada mes", b: "Fer una megafesta cada mes" }
    ],
    picant: [
      { a: "Que el teu ex et vegi el mòbil", b: "Que els teus pares vegin el teu mòbil" },
      { a: "Besar tothom del grup", b: "Mostrar l'última foto de la galeria a tothom" },
      { a: "Que tothom vegi els teus DMs", b: "Que tothom vegi el teu historial de navegació" },
      { a: "Un rotllo increïble amb algú lleig", b: "Un rotllo terrible amb algú guapíssim" },
      { a: "No poder besar mai més", b: "No poder abraçar mai més" },
      { a: "Que el teu millor amic sàpiga tots els teus secrets sexuals", b: "Que un desconegut sàpiga tots els teus secrets sexuals" },
      { a: "Estar amb la mateixa persona per sempre", b: "Estar amb una persona diferent cada mes" },
      { a: "Sexe increïble sense amor", b: "Amor increïble sense sexe" },
      { a: "Que et vegin plorant", b: "Que et vegin en una situació íntima" },
      { a: "Enviar un nude accidentalment al grup de família", b: "Que el teu ex publiqui una foto teva vergonyosa" },
      { a: "Tenir una relació oberta", b: "Tenir una relació a distància" },
      { a: "Mai poder dir mentides", b: "Mai saber si et diuen la veritat" },
      { a: "Perdre tots els records amb la teva parella", b: "Que la teva parella perdi els records amb tu" },
      { a: "Viure amb el teu ex per sempre", b: "No tenir mai més parella" },
      { a: "Que la gent sàpiga quan estàs excitat/da", b: "Que la gent sàpiga quan estàs mentint" }
    ]
  },

  // ===================== L'IMPOSTOR =====================
  impostor: {
    animals: [
      { word: "Gos", similar: "Llop" },
      { word: "Gat", similar: "Tigre" },
      { word: "Àguila", similar: "Falcó" },
      { word: "Dofí", similar: "Balena" },
      { word: "Cavall", similar: "Zebra" },
      { word: "Elefant", similar: "Rinoceront" },
      { word: "Lleó", similar: "Pantera" },
      { word: "Conill", similar: "Llebre" },
      { word: "Serp", similar: "Llangardaix" },
      { word: "Pingüí", similar: "Foca" },
      { word: "Abella", similar: "Vespa" },
      { word: "Rata", similar: "Hàmster" },
      { word: "Tortuga", similar: "Cocodril" },
      { word: "Papagai", similar: "Canari" },
      { word: "Formiga", similar: "Escarabat" }
    ],
    menjar: [
      { word: "Pizza", similar: "Coca" },
      { word: "Sushi", similar: "Sashimi" },
      { word: "Hamburguesa", similar: "Entrepà" },
      { word: "Paella", similar: "Arròs a la cubana" },
      { word: "Gelat", similar: "Granissat" },
      { word: "Xocolata", similar: "Cacau" },
      { word: "Cervesa", similar: "Sidra" },
      { word: "Cafè", similar: "Té" },
      { word: "Croissant", similar: "Ensaïmada" },
      { word: "Pasta", similar: "Fideus" },
      { word: "Tacos", similar: "Burritos" },
      { word: "Creps", similar: "Tortitas" },
      { word: "Croquetes", similar: "Nuggets" },
      { word: "Vi", similar: "Cava" },
      { word: "Truita", similar: "Ou ferrat" }
    ],
    llocs: [
      { word: "Platja", similar: "Piscina" },
      { word: "Hospital", similar: "Clínica" },
      { word: "Escola", similar: "Universitat" },
      { word: "Cinema", similar: "Teatre" },
      { word: "Supermercat", similar: "Mercat" },
      { word: "Aeroport", similar: "Estació de tren" },
      { word: "Biblioteca", similar: "Llibreria" },
      { word: "Discoteca", similar: "Bar" },
      { word: "Gimnàs", similar: "Poliesportiu" },
      { word: "Museu", similar: "Galeria d'art" },
      { word: "Restaurant", similar: "Cafeteria" },
      { word: "Parc", similar: "Jardí" },
      { word: "Hotel", similar: "Hostal" },
      { word: "Farmàcia", similar: "Herbolari" },
      { word: "Zoo", similar: "Aquàrium" }
    ],
    pelis: [
      { word: "Harry Potter", similar: "El Senyor dels Anells" },
      { word: "Star Wars", similar: "Star Trek" },
      { word: "Titanic", similar: "Pearl Harbor" },
      { word: "Batman", similar: "Spiderman" },
      { word: "Matrix", similar: "Inception" },
      { word: "Toy Story", similar: "Monsters Inc" },
      { word: "El Rei Lleó", similar: "El Llibre de la Selva" },
      { word: "Frozen", similar: "Vaiana" },
      { word: "Fast & Furious", similar: "Need for Speed" },
      { word: "Jurassic Park", similar: "King Kong" },
      { word: "La Casa de Papel", similar: "Breaking Bad" },
      { word: "Friends", similar: "How I Met Your Mother" },
      { word: "Stranger Things", similar: "Dark" },
      { word: "Squid Game", similar: "Hunger Games" },
      { word: "Avatar", similar: "Interstellar" }
    ],
    professions: [
      { word: "Metge", similar: "Infermer" },
      { word: "Professor", similar: "Tutor" },
      { word: "Policia", similar: "Guàrdia de seguretat" },
      { word: "Cuiner", similar: "Pastisser" },
      { word: "Arquitecte", similar: "Enginyer" },
      { word: "Pilot", similar: "Astronauta" },
      { word: "Fotògraf", similar: "Càmera" },
      { word: "Cantant", similar: "Músic" },
      { word: "Actor", similar: "Presentador" },
      { word: "Bomber", similar: "Socorrista" },
      { word: "Advocat", similar: "Jutge" },
      { word: "Periodista", similar: "Escriptor" },
      { word: "Dentista", similar: "Oculista" },
      { word: "Mecànic", similar: "Electricista" },
      { word: "Perruquer", similar: "Maquillador" }
    ],
    objectes: [
      { word: "Mòbil", similar: "Tablet" },
      { word: "Cadira", similar: "Tamboret" },
      { word: "Rellotge", similar: "Temporitzador" },
      { word: "Mirall", similar: "Finestra" },
      { word: "Guitarra", similar: "Ukelele" },
      { word: "Bicicleta", similar: "Patinet" },
      { word: "Paraigua", similar: "Para-sol" },
      { word: "Sabata", similar: "Sandàlia" },
      { word: "Llibre", similar: "Revista" },
      { word: "Clau", similar: "Cadenat" },
      { word: "Coixí", similar: "Manta" },
      { word: "Tisores", similar: "Cúter" },
      { word: "Motxilla", similar: "Maleta" },
      { word: "Llanterna", similar: "Espelma" },
      { word: "Casc", similar: "Gorra" }
    ]
  }
};
